library(covidData)
library(covidHubUtils)
# covidHubUtils::preprocess_nytimes("./covid19-forecast-hub/data-truth/nytimes/")
# covidHubUtils::preprocess_jhu("./covid19-forecast-hub/data-truth/")
# covidHubUtils::preprocess_visualization_truth("./covid19-forecast-hub/visualization/vis-master/covid-csv-tools/dist/truth")
covidHubUtils::preprocess_hospitalization("./covid19-forecast-hub/data-truth/")
# covidHubUtils::save_truth_for_zoltar("./covid19-forecast-hub/data-truth/")
