install.packages('devtools')
devtools::install_github('reichlab/zoltr')
devtools::install_github('epiforecasts/scoringutils')
devtools::install_github('reichlab/covidHubUtils')
install.packages(c('tidyverse', 'rvest', 'here', 'covidcast'))
